hypertrace/hypertrace-service

- README.md
This PR adds
- federated service architecture wrt Hypertrace query architecture.
- working of federated service
- build steps and image source
> adds federated service architecture and explains working

- .gitmodules
- hypertrace-federated-service/build.gradle.kts
- hypertrace-federated-service/src/main/java/org/hypertrace/federated/service/BootstarpTimerTask.java
- hypertrace-federated-service/src/main/java/org/hypertrace/federated/service/BootstrapTimerTask.java
- hypertrace-federated-service/src/main/java/org/hypertrace/federated/service/FederatedService.java
- hypertrace-federated-service/src/main/java/org/hypertrace/federated/service/HypertraceUIServer.java
- hypertrace-federated-service/src/main/java/org/hypertrace/federated/service/HypertraceUIServerTimerTask.java
- hypertrace-federated-service/src/main/resources/configs/config-bootstrapper/application.conf
- hypertrace-federated-service/src/main/resources/configs/hypertrace-federated-service/application.conf
- settings.gradle.kts
- adds a background task for bootstrapping attributes
- also adds a few config envs like - shouldExit on failure, max retries, and delay interval in each retry.
These changes will help in the reduction of the config-bootstrap containers in a local HT setup mode.
> Adds a background task for bootstrapping attributes

- build.gradle.kts
New functionality isn't used as the docker setup is custom here.
However, this might help tell the difference between what is failing
on PR branch vs main
See #26
> Moving docker plugin to latest

- .circleci/config.yml
https://app.circleci.com/pipelines/github/hypertrace/hypertrace-service/135/workflows/d8a5141f-41b4-4da9-85f0-26c2ba52522a/jobs/387
> adding remote-docker setup task for publish issu

- hypertrace-service/src/main/java/org/hypertrace/service/HypertraceUIServer.java
Reverts hypertrace/hypertrace-service#34
> Revert "redirecting to index.html for deep paths"

- hypertrace-service/src/main/java/org/hypertrace/service/HypertraceUIServer.java
fixes the issue - hypertrace/hypertrace#71
> fixes broker link issue by redircting to index.html for deep links

- hypertrace-service/src/main/java/org/hypertrace/service/HypertraceUIServerTimerTask.java
- hypertrace-service/src/main/resources/configs/hypertrace-service/application.conf
- hypertrace-service/src/main/resources/log4j2.properties
Address the issue - https://github.com/hypertrace/query-service/issues/29
> Fixes startup exceptions happens which happens before dependent services is up 

- hypertrace-service/src/main/java/org/hypertrace/service/HypertraceService.java
- hypertrace-service/src/main/resources/configs/hypertrace-graphql-service/default-cluster/application.conf
Update to latest GQL submodule
Build and ran locally
- [n/a] My changes generate no new warnings
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [n/a] Any dependent changes have been merged and published in downstream modules
> chore: update gql

- hypertrace-service/build.gradle.kts
> resolves snyk failure

- README.md
adds local testing steps in README.
> adds testing steps

- .github/workflows/pr-build.yml
- .snyk
Updating snyk expirations for issues with no upgrade paths
> chore: update snyk expirations without upgrade path

- .gitmodules
- hypertrace-service/build.gradle.kts
- hypertrace-service/src/main/java/org/hypertrace/service/HypertraceService.java
- hypertrace-service/src/main/resources/configs/config-service/defaut-cluster/application.conf
- hypertrace-service/src/main/resources/configs/hypertrace-graphql-service/default-cluster/application.conf
- settings.gradle.kts
This adds the config service to hypertrace-service's collection of services, and updates other services to latest. This service is needed to support hypertrace/hypertrace#142 , and will power other config-driven features in the future.
Built this image locally and verified it in a local docker-compose deployment.
> chore: add config service and update others to latest

- hypertrace-service/src/main/resources/configs/config-service/default-cluster/application.conf
- Updates submodules references
- Corrects the cluster name of config-service
- Adds postgres settings for config-service
- Verified locally
None
> chore: updates submodules references and minor fixes

- README.md
This PR, 
- Updated architecture diagram for query layer architecture in README
- Updated details of hypertrace-service
NA
- https://docs.hypertrace.org/arch/
> docs: updates architecture diagram and added details in README

- hypertrace-data-config-service/build.gradle.kts
- hypertrace-data-query-service/build.gradle.kts
- hypertrace-service/build.gradle.kts
- Update submodule referece of config-bootstrapper, config-service, attribute and entity service
- Updates doc-store version to include postgres impl of exists, not-exists, and NEQ filters
- hypertrace/document-store#35
- hypertrace/document-store#33
> chore: Update sub-modules reference and doc store version

- hypertrace-data-config-service/helm/Chart.yaml
> chore: Update bootstrapper version

- hypertrace-data-config-service/helm/Chart.yaml
- updates version of config-bootstrapper chart.
> fix: update config-bootstrapper version

- hypertrace-data-config-service/helm/Chart.yaml
Updated submodules to get changes for adding `backend_destination` column.
NA
> chore: updated submodules for backend_destination changes

- .snyk
- hypertrace-data-config-service/build.gradle.kts
- hypertrace-data-query-service/build.gradle.kts
- hypertrace-service/build.gradle.kts
> chore: update vulnerabilities

- hypertrace-data-config-service/helm/Chart.yaml
updates submodules for changes related to addition of api trace error count attribute. 
NA
> chore: updates submodules and version of config bootstrapper

- hypertrace-data-config-service/helm/Chart.yaml
- updates submodule references to latest head
> chore: updates submodules references

- .snyk
- incorporate latest changes from submodules
> chore: update submodule reference to latest

- hypertrace-service/src/main/resources/configs/hypertrace-graphql-service/default-cluster/application.conf
> Default GQL Downstream Client Timeout Values and Updated Submodule Refs

- .snyk
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle.kts
Update submodule and gradle version
> chore: Update submodule

- hypertrace-data-config-service/build.gradle.kts
- hypertrace-data-query-service/build.gradle.kts
- hypertrace-service/build.gradle.kts
> fix: update vuln deps

- hypertrace-data-config-service/build.gradle.kts
- hypertrace-data-query-service/build.gradle.kts
- hypertrace-service/build.gradle.kts
Please include a summary of the change, motivation and context.
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested helm chart locally. 
Make sure that you have documented corresponding changes in this repository or [hypertrace docs repo](https://github.com/hypertrace/hypertrace-docs-website) if required.
> chore: update log4j version to 2.17.0
